version: "2.7"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - PORT=${APP_PORT}
        - NODE_ENV=${NODE_ENV}
    env_file:
      - ./.env
    user: node
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - mongo
    networks:
      - mynet
    command: "yarn start:dev"

  cart:
    extends:
      file: ./kk-cart/docker-compose.yml
      service: cart
    depends_on:
      - postgres
    networks:
      - mynet

  product:
    extends:
      file: ./kk-product/docker-compose.yml
      service: product
    depends_on:
      - mongo
    networks:
      - mynet

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mynet

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    networks:
      - mynet

  mongo:
    image: mongo:latest
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - db-data:/data/db
    networks:
      - mynet

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASSWORD}
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
    depends_on:
      - mongo
    networks:
      - mynet

volumes:
  db-data:

networks:
  mynet:
